name: Brandt Lab
author: Veronica Brandt
markdown: redcarpet
highlighter: pygments
#url: http://veromary.github.io/brandt.id.au
#url: http://localhost:4000
url: http://www.brandt.id.au
email: veroicon@gmail.com
GOOGLE_ANALYTICS: UA-39801667-1
DISQUS_SITENAME: brandtlab

FEED_RSS: http://feeds.feedburner.com/brandtlab

collections:
  biblestudy:
    output: true
