name: Brandt Lab
markdown: redcarpet
pygments: true
#url: http://veromary.github.io/brandt.id.au
#url: http://localhost:4000
url: http://brandt.id.au
email: allofus@brandt.id.au
ftp_host: ftp.repleatur.net
ftp_dir: /
ftp_passive: false
GOOGLE_ANALYTICS: UA-39801667-1
DISQUS_SITENAME: brandtlab

# optional
ftp_port: 21                  # default 21
ftp_username: 'brandt@repleatur.net'     # default read from stdin
ftp_password: '*ooluG4mct@B' # default read from stdin


